# you describe your data using the YAML notation here
# and then load them using Fixtures.load("data.yml")

Configuration(1):
    gameSessionLength : 60
    infoPanelRollTime : 20
    pointsForCorrectAnswer :  2
    pointsForInCorrectAnswer : -1
    defaultArenaResolution : 720p